// backflip20.h -- generated by sim2real/make_backflip20.py
// source: mp2_backflip_v5a_20hz_bf20.csv
//
// 9 frames, 2.10 s total (edited).
// IDEAL SCS counts: 511 == the 70 mm stand. The firmware adds this
// robot's offset[] at playback, so recalibrating does not invalidate
// this table.
//
// Servo id order 1..12 (FR abd/thigh/calf, FL, RR, RL); [0] unused.
// Column 1/4/7/10 (abduction) stays at centre - the planner locks it.
#pragma once
#include <stdint.h>

#define BF20_FRAMES 9
#define BF20_SOURCE "mp2_backflip_v5a_20hz_bf20.csv"

static const uint16_t BF20_COUNTS[BF20_FRAMES][13] = {
    {   0,  511,  472,  346,  511,  550,  676,  511,  387,  490,  511,  635,  532},
    {   0,  511,  473,  389,  511,  549,  633,  511,  361,  504,  511,  661,  518},
    {   0,  511,  508,  453,  511,  514,  569,  511,  346,  497,  511,  676,  525},
    {   0,  511,  644,  526,  511,  378,  496,  511,  449,  464,  511,  573,  558},
    {   0,  511,  704,  460,  511,  319,  561,  511,  444,  565,  511,  578,  457},
    {   0,  511,  811,  319,  511,  209,  703,  511,  312,  850,  511,  710,  172},
    {   0,  511,  777,  298,  511,  242,  729,  511,  334,  762,  511,  689,  260},
    {   0,  511,  538,  423,  511,  481,  602,  511,  565,  411,  511,  455,  614},
    {   0,  511,  468,  483,  511,  554,  539,  511,  559,  472,  511,  463,  549},
};

static const uint16_t BF20_MOVE_MS[BF20_FRAMES] = { 800, 125, 50, 50, 40, 40, 100, 100, 100 };
static const uint16_t BF20_DELAY_MS[BF20_FRAMES] = { 300, 0, 0, 0, 0, 0, 0, 0, 0 };
