// mp2_calib.h  -- AUTO-GENERATED by export_to_robot.py (SINGLE SOURCE OF TRUTH)
// Shared servo calibration for EVERY exported motion.
// servo_write(id, BF_SIGN[id-1]*(URDF_DEG - BF_STAND[id-1]) + offset[id])
//   offset[] = live stand calibration on the robot (set with `setcal`).
// hardware remap applied: SWAP_LR=False, SWAP_HIP_KNEE=True
// (so these arrays are in PHYSICAL servo-id order, matching the frames)
// Measured neutral stance this was built against (recdump row 0):
//   57,662,600,50,557,445,51,543,533,49,485,483
#pragma once

static const float BF_STAND[12] = { 0, -90, 45, 0, -90, 45, 0, -90, 45, 0, -90, 45 };
static const float BF_SIGN[12]  = { +1, +1, +1, +1, -1, -1, +1, +1, +1, +1, -1, -1 };
