// mp2_backflip2_data.h  -- AUTO-GENERATED by export_to_robot.py
// source: backflip_edit.py
// 8 frames, servo id order 1..12 (FR abd/hip/knee, FL, RR, RL), URDF degrees.
// no L/R swap applied.
// Firmware maps to servos via BF_SIGN[]/BF_STAND[] + your offset[] calibration.
#pragma once
#define BF2_FRAMES 8

static const float BF2_URDF_DEG[BF2_FRAMES][12] = {
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },
  {     0.00f,  -145.50f,    68.20f,     0.00f,  -145.50f,    68.20f,     0.00f,  -129.50f,    68.20f,     0.00f,  -129.50f,    68.20f },
  {     0.00f,  -131.20f,    25.20f,     0.00f,  -131.20f,    25.20f,     0.00f,   -32.40f,   -16.20f,     0.00f,   -32.40f,   -16.20f },
  {     0.00f,   -37.80f,    25.20f,     0.00f,   -37.80f,    25.20f,     0.00f,   -32.40f,   -16.20f,     0.00f,   -32.40f,   -16.20f },
  {     0.00f,   -37.80f,    25.20f,     0.00f,   -37.80f,    25.20f,     0.00f,   -27.00f,   106.00f,     0.00f,   -27.00f,   106.00f },
  {     0.00f,   -75.60f,   -24.30f,     0.00f,   -75.60f,   -24.30f,     0.00f,   -27.00f,   106.00f,     0.00f,   -27.00f,   106.00f },
  {     0.00f,   -75.60f,   -24.30f,     0.00f,   -75.60f,   -24.30f,     0.00f,  -122.60f,    59.60f,     0.00f,  -122.60f,    59.60f },
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },
};
