// mp2_caltest_data.h  -- AUTO-GENERATED by export_to_robot.py
// source: cal-test (both)
// 9 frames, servo id order 1..12 (FR abd/hip/knee, FL, RR, RL), URDF degrees.
// no L/R swap applied.
// Firmware maps to servos via BF_SIGN[]/BF_STAND[] + your offset[] calibration.
#pragma once
#define CAL_FRAMES 9

static const float CAL_URDF_DEG[CAL_FRAMES][12] = {
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // neutral
  {     0.00f,   -90.00f,    45.00f,     0.00f,  -140.00f,    70.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // front-LEFT leg
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // neutral
  {     0.00f,  -140.00f,    70.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // front-RIGHT leg
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // neutral
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,  -140.00f,    70.00f },  // back-LEFT leg
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // neutral
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,  -140.00f,    70.00f,     0.00f,   -90.00f,    45.00f },  // back-RIGHT leg
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },  // neutral
};
