// BFV1_data.h  -- AUTO-GENERATED by hdf5_tools.py
// source: bfv1.hdf5
// 5 frames, servo id order 1..12 (FR abd/hip/knee, FL, RR, RL), URDF degrees.
// no L/R swap applied.
// Firmware maps to servos via BF_SIGN[]/BF_STAND[] + your offset[] calibration.
#pragma once
#define BFV1_FRAMES 5

static const float BFV1_T[BFV1_FRAMES] = { 0.000f, 0.013f, 0.025f, 0.038f, 0.050f };

static const float BFV1_URDF_DEG[BFV1_FRAMES][12] = {
  {     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f,     0.00f,   -90.00f,    45.00f },
  {     0.00f,   -88.60f,    42.74f,     0.00f,   -88.65f,    42.83f,     0.00f,   -88.60f,    42.74f,     0.00f,   -88.65f,    42.83f },
  {     0.00f,   -90.41f,    42.11f,     0.00f,   -89.22f,    40.08f,     0.00f,   -90.41f,    42.11f,     0.00f,   -89.22f,    40.08f },
  {     0.00f,   -86.79f,    38.19f,     0.00f,   -87.71f,    39.74f,     0.00f,   -86.79f,    38.19f,     0.00f,   -87.71f,    39.74f },
  {     0.00f,   -81.55f,    32.16f,     0.00f,   -84.97f,    37.73f,     0.00f,   -81.55f,    32.16f,     0.00f,   -84.97f,    37.73f } 
};
